### ISSUE TITLE
Implementar Diagrama de Atividades

### ISSUE THREAD

**Issue by nicol4ss** [Superbad-Group/ES-Game-Lasca#14]

**Comment by anthongretter** [comment]
# Avaliar Jogada
## Erros Apontados:

- Emissão da operação de empilhamento da peça capturada

### Antes:
![image](https://user-images.githubusercontent.com/70354378/171974733-4c296b03-0dbc-4f1c-b1cc-48216c573330.png)


### Solução Sugerida:
![image](https://user-images.githubusercontent.com/70354378/171974791-bd5198b4-32b2-4e7f-9f47-ece922b6df56.png)

**Comment by anthongretter** [comment]
# Interagir com Tabuleiro
## Erros Apontados:

- Organização do diagrama ( no way someone can read this without becoming insane 0_o )
- Emissão do caso de uso auxiliar **Efetuar Jogada** (talvez não tem problema)
   - **CASO ELE SEJA REFERENCIADO AQUI TERIA Q SER "INCLUDE" E N "EXTENDED" NO DIAGRAMAS DE CASOS DE USO**
 
   - Comment:
     > Pensei assim pq Efetuar Jogada (selecionar um destino)
     > também n deixa de ser uma interação com o tabuleiro

### Antes:
![image](https://user-images.githubusercontent.com/70354378/171981180-ba3f1cff-ccbe-44bc-9d6b-cb89b6001658.png)

### Solução Sugerida:
![image](https://user-images.githubusercontent.com/70354378/171981225-19bbb3f1-73f9-4284-a256-46aa5ce81aae.png)

**Comment by anthongretter** [comment]
# Notas

- Revisar Diagrama de Casos de Uso em conjunto (dado alterações e para esclarecimentos)
- Revisar Diagramas de Sequência em conjunto (muito confuso pra ler, capaz de eu fazer merda sozinho)
